apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.name }}
  labels:
   appName: {{ .Values.name }}
spec:
  containers:
    - name: {{ .Values.name }}
      image: public.ecr.aws/w8x4g9h7/roboshop-v3/{{ .Values.name }}
      env:
{{- toYaml .Values.env | indent 6 }}   ####indent is sapces you want to give
     


#### git pull ; helm install catalogue ./ -f env-dev/catalogue.yml