

{{- if .Values.schema.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}
  labels:
    appName: {{ .Values.name }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
spec:
    template:
      containers:
       - name: schema-load
         image: 640168456211.dkr.ecr.us-east-1.amazonaws.com/schema-load:latest
         imagePullPolicy: Always
         envFrom:
         - secretRef:
           name: {{ .Values.name }}   
      restartPolicy: Never
    backoffLimit: 0
{{- end -}}

