### applying condition onschema
####### {{ if .Values.something }}
####content of yaml file
#####{{ end }}

{{- if .Values.schema.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}
  labels:
   appName: {{ .Values.name }}
spec:
  template:
    spec:
      containers:
      {{- range $k, $v := .Values.schema.containers }}  ########### loop in range
      - name: {{ $K }}
        image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load    
        env:
          {{- toYaml .$Values.schema.env | nindent 12 }}
          - name: SCHEMA_FILE
            value: db/{{ $v }}
      {{- end -}} 
      restartPolicy: Never
  backoffLimit: 0
{{- end -}}
